FROM japaric/x86_64-unknown-linux-musl:v0.1.14

RUN apt-get update && \
    apt-get install -y xorg-dev libx11-xcb-dev libxcb1-dev libxcb-shm0-dev libxcb-randr0-dev libxcb-randr0 libxrandr2 libxrandr-dev x11proto-randr-dev
RUN apt-get install -y python3
RUN apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
RUN apt-get install -y libxcb1-dev \
                       libxcb-util0-dev \
                       libxcb-randr0-dev \
                       libxcb-composite0-dev
RUN apt-get install -y build-essential git cmake cmake-data pkg-config libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev
# docker build -t my/x86_64-unknown-linux-musl --file=Dockerfile.x86_64-unknown-linux-musl .
