name: ncscreenier
base: core18 # the base snap is the execution environment for this snap
version: '0.1'
summary: Screenshot + crop + upload
description: |
  Tbd

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  main:
    source: .
    plugin: rust
    #build-attributes: [no-system-libraries]
    build-packages:
      - libssl-dev
      - pkg-config
      - make
      - libx11-xcb-dev
      - libxcb-shm0-dev
      - libxcb-randr0-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - python3
    stage-packages:
      - libssl1.0.0
      - libstdc++6
      - libx11-6
      - libx11-xcb1
      - libxcb-shm0
      - libxcb-randr0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxau6
      - libxdmcp6
      - libxcursor1
      - libxfixes3
      - libxi6
      - libxrandr2
      - libxrender1
apps:
  ncscreenier:
    command: ncscreenier
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
